### PR TITLE
Working toward a good plugin for a Foam 

### PR DESCRIPTION
**Pull request by fletchermoore**
Great extension. Adding some features. See if you want any of them. Described what I did in the top of the readme.

### CODE REVIEW

**Comment by jasonwilliams** [comment]
Hey these looks good thanks, ill take a look when I have some time.
What is your plan with this? Are you hoping to have a fork which works with Foam? Or just planning to push new features upstream?

Whats the difference between running this extension and having a foam plugin?
Jason

**Comment by fletchermoore** [comment]
Hey, I sent you the pull because I wanted to engage you. This pull is actually already out of date. Haha. Personally, I just got started making a foam personal knowledge base and wanted my curation of that to be reflected automatically in Anki. I would have started from the ground up, but your plugin using Anki connect was exactly the kind of strategy I had in mind so it was nice. 

Foam's design principles seem to be more or less a recommended collection of extensions. However, this kind of thing does not need to know about or interact directly with Foam, I don't think. But maybe Foam project would recommend it if it played nice.

My target for the extension is to essentially send cards to Anki, and then to watch for changes to those files (probably by attaching some metadata at the file end), and have Anki automatically updated on save. 

Secondarily, I think there are multiple strategies that could be employed to turn markdown into flashcards. It is somewhat arbitrary. Long ago I settled on a way of doing with bullet lists that made note taking faster for me. I just wanted to implement that as well.

So my question is: would you like me to keep adding features to your project or release my own extension? As I am working on it now, all my additional features should be non-default additions that the user can enable. So I think it would be fine to merge them at some point, rather than have people find multiple extensions that do similar things on the vscode search.

**Comment by jasonwilliams** [comment]
The origin of this extension is here https://github.com/foambubble/foam/issues/140 I’m sure they would have no issues recommending it.

it doesn’t need to know or care about Foam, many people using it don’t use foam either, so that’s why it’s a separate agnostic extension.

Yes updating on save would be nice, and some of the changes look good. But I don’t think this PR is a wholesale merge though. I will need to check it out and try it. Maybe it’s better to break up some of the features and merge them in one by one? If that’s not possible maybe you could update the PR for me to look through.

But yeah I’m happy to work with you on this instead of multiple extensions floating about

**Comment by fletchermoore** [comment]
OK great. I didn't realize you were also inspired by Foam before I started. I am going to start an issue so we can talk about update on save.

**Comment by fletchermoore** [comment]
I'm going to close this pull request. Unfortunately it might be more difficult to untangle the individual features. I've added at this point. I'll send you another one after I add the auto-save feature. Then I'll start sending small more manageable requests.

**Pull request closed without merging**
