### PR TITLE
Fixed deck name pulling more than just the header

### PR DESCRIPTION
**Pull request by MicahGV**
Fix for issue #24

### CODE REVIEW

**Comment by MicahGV** [comment]
Tell me if you want me to do anything extra

**Comment by jasonwilliams** [comment]
Thanks @MicahGV 
A test would be good, similar to what I did here https://github.com/jasonwilliams/anki/blob/master/src/markdown/parsers/__tests__/cardParser.test.ts

**Comment by MicahGV** [comment]
Sure man

**Comment by MicahGV** [comment]
I ended up adding some additional linter config so when I created new files I wouldn't have to care about swapping it over from my default. Also, I hope it's alright if I only focused on the deckName method for the tests.

**Comment by jasonwilliams** [comment]
@MicahGV this is fantastic, those tests are awesome. 
Thanks!

**Pull request merged**
